spring:
  application:
    name: ap4

  datasource:
    url: jdbc:hsqldb:mem:ap4db;DB_CLOSE_DELAY=-1
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
